Custom margins
lienputnina/react-components-for-you pull request #3
Opened 2022-10-20 08:06 UTC by lienputnina

2022-10-20 17:07 UTC, kputnins commented on src/styles/stories/Paddings/PaddingExample.tsx
> +    <p className="padding-text">{`Padding size :${getPaddingSizeValue(
This change from `div` to `p` has introduced an unintended bug in padding story
![image](https://user-images.githubusercontent.com/36342248/197012612-45819718-7099-48d0-9dae-b2b39b02183b.png)

This is because `p` has innate margins. You change `p` back to `div` and put the paragraph tag inside liek so:
```ts
<div className="padding-text"><p>{`Padding size :${getSizeValue(size)}`}</p></div>
```

On a related note - we should do a `style reset` to skip such problems.
I'll find some reference material and add it as a seperate comment

2022-10-20 17:18 UTC, kputnins commented on src/styles/stories/Margins/MarginExample.tsx
> +import { FC } from 'react';
Lets use `import type` [TS feature](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) 
```suggestion
import type { FC } from 'react';
```

2022-10-20 17:20 UTC, kputnins commented on src/styles/stories/Margins/MarginExample.tsx
> +  extends React.HTMLAttributes<HTMLDivElement> {
In this and Padding story you don't need to extend HTML element interface for your pros if you are not going to provide any props to the HTML element.
Ask me about this offline if you didn't get it

2022-10-20 17:28 UTC, kputnins commented on src/styles/stories/Margins/MarginExample.tsx
> +    </div>
You can extract this `div` in a function and then call it here 2 times

```tsx
const renderInnerDiv = (size: string) => (
  <div className={classNames("margin", `margin-${size}`)}>
    <p className="margin-text">{`Margin size :${getMarginSizeValue(size)}`}</p>
  </div>
);
```

2022-10-20 17:31 UTC, kputnins commented
No version bump :cry:

2022-10-20 17:36 UTC, kputnins commented
I know it is outside the scope of this ticket, but please add [this CSS Reset](https://www.joshwcomeau.com/css/custom-css-reset/)
1. Create a `cssReset.scss` file with the css code in the article
2. Put it inside `react-components-for-you/src/styles/scss/`
3. Import that file in `index.scss` with comment `CSS Reset from https://www.joshwcomeau.com/css/custom-css-reset/`

Original [issue](https://github.com/lienputnina/react-components-for-you/pull/3#discussion_r1000903868)

2022-10-26 15:41 UTC, kputnins requested changes
Left one comment about double import - otherwise LGTM

2022-10-26 15:41 UTC, kputnins commented on src/index.scss
> +
`cssReset.scss` is currently double imported - here and in `./styles/scss/global.scss`

I think it semantically makes sense to:
- import it in `global.scss` (move explaining comment there)
- import `global.scss` to all stories in `preview.js`
- remove this import

2022-10-26 15:42 UTC, kputnins commented on src/styles/stories/Margins/MarginExample.tsx
> +  extends React.HTMLAttributes<HTMLDivElement> {
Discussed offline

2022-10-26 15:45 UTC, kputnins commented on src/styles/stories/Margins/MarginExample.tsx
> +    <p className="margin-text">{`Margin size :${getMarginSizeValue(size)}`}</p>
Both `Padding` and `Margin` stories in their content text have a space before the colon and no space after

![image](https://user-images.githubusercontent.com/36342248/198073076-75d678f8-75db-4037-abb3-5e54585de7b1.png)

2022-10-27 11:45 UTC, lienputnina commented on src/index.scss
> +
I see the point. Question though - currently we  have the following system:
- **global.scss** has the **cssReset** import
- **index.scss** has **global.scss**, **colors.scss** and **Button.scss** imported. 
Do we need to import both **margins.scss** and **paddings.scss** in **global** or **index**? They are now imported in the scss files of Margin and Padding components, which are using them for classes.

2022-10-27 15:33 UTC, kputnins commented on src/index.scss
> +
No we do not need to import the story styles to `index.scss`.

Think of it in this way: `index.scss` is all of the styles you want to make available to the consumer of this library
The consumer of the library does not need styles for stories that are only available in the Storybook static page.
Remember that `stories != components`
The library exposes components, but internalizes everything else

2022-10-27 15:34 UTC, kputnins commented on src/index.scss
> +
You wrote `They are now imported in the scss files of Margin and Padding components, which are using them for classes.`

The conceptually correct statement would be `They are now imported in the scss files of Margin and Padding **story** components, which are using them for classes.`

2022-10-27 15:55 UTC, kputnins approved these changes

2022-10-27 15:56 UTC, merged